<?php
/**
 * Anlage EÜR 2025: line layout and code → line mapping.
 *
 * Source: BMF, Vordruck "Anlage EÜR 2025" (BMF-Schreiben 29.08.2025) and "Anleitung zur Anlage EÜR 2025".
 * Only this file changes when the official form changes; account → code mapping stays.
 *
 * codes:  code => [line, ku_line (set: revenue of a Kleinunternehmer document goes to code E_KU / line 12),
 *                  col ('nabz' for "nicht abziehbar"), split (share per column for lines 62–67),
 *                  gross (input VAT not deductible, § 15 Abs. 1a UStG: expense is entered gross, not in line 57)]
 *         A code without 'line' is not part of the form (neutral cash flows).
 * lines:  line => [label, section, twocol (lines 62–67), sum (line => sign), manual (only filled manually)]
 *         Sums use the "abziehbar" column of two-column lines.
 */

return array(
	'year' => 2025,
	'codes' => array(
		// 1. Betriebseinnahmen
		'E_KU'           => array('line' => 12),
		'E_UMS_STPFL'    => array('line' => 15, 'ku_line' => 12),
		'E_UMS_FREI'     => array('line' => 16, 'ku_line' => 12),
		'E_UST'          => array('line' => 17),
		'E_UST_ERST'     => array('line' => 18),
		'E_AV_VERK'      => array('line' => 19),
		'E_KFZ_PRIV'     => array('line' => 20),
		'E_ENTN_SONST'   => array('line' => 21),
		'E_RUECKL'       => array('line' => 22),
		// 2. Betriebsausgaben
		'A_PAUSCH'       => array('line' => 24),
		'A_WAREN'        => array('line' => 27),
		'A_FREMDL'       => array('line' => 29),
		'A_PERSONAL'     => array('line' => 30),
		'A_AFA_GRUND'    => array('line' => 31),
		'A_AFA_IMMAT'    => array('line' => 32),
		'A_AFA_BEW'      => array('line' => 33),
		'A_SONDER_AFA'   => array('line' => 34),
		'A_7G_HERAB'     => array('line' => 35),
		'A_GWG'          => array('line' => 36),
		'A_SAMMELP'      => array('line' => 37),
		'A_RESTBW'       => array('line' => 38),
		'A_RAUM'         => array('line' => 39),
		'A_DOPPHH'       => array('line' => 40),
		'A_GRUNDST'      => array('line' => 41),
		'A_TELEKOM'      => array('line' => 43),
		'A_REISE'        => array('line' => 44),
		'A_FORTB'        => array('line' => 45),
		'A_BERATUNG'     => array('line' => 46),
		'A_MIETE_BEW'    => array('line' => 47),
		'A_ERHALT'       => array('line' => 48),
		'A_BEITRAEGE'    => array('line' => 49),
		'A_EDV'          => array('line' => 50),
		'A_ARBEITSM'     => array('line' => 51),
		'A_ENTSORG'      => array('line' => 52),
		'A_TRANSPORT'    => array('line' => 53),
		'A_WERBUNG'      => array('line' => 54),
		'A_ZINS_AV'      => array('line' => 55),
		'A_ZINS'         => array('line' => 56),
		'A_VST'          => array('line' => 57),
		'A_UST_FA'       => array('line' => 58),
		'A_RUECKL'       => array('line' => 59),
		'A_UEBRIGE'      => array('line' => 60),
		'A_GESCH_ABZ'    => array('line' => 62),
		'A_GESCH_NABZ'   => array('line' => 62, 'col' => 'nabz', 'gross' => 1),
		'A_BEWIRT'       => array('line' => 63, 'split' => array('abz' => 0.7, 'nabz' => 0.3)),
		// Bewirtung: input VAT stays deductible also for the non-deductible 30 % (§ 15 Abs. 1a Satz 2 UStG)
		'A_BEWIRT_NABZ'  => array('line' => 63, 'col' => 'nabz'),
		'A_VERPFL'       => array('line' => 64),
		'A_ARBZI'        => array('line' => 65),
		'A_ARBZI_NABZ'   => array('line' => 65, 'col' => 'nabz', 'gross' => 1),
		'A_HOMEOFFICE'   => array('line' => 66),
		'A_SONST_BESCHR' => array('line' => 67),
		'A_SONST_NABZ'   => array('line' => 67, 'col' => 'nabz', 'gross' => 1),
		'A_KFZ_LEAS'     => array('line' => 68),
		'A_KFZ_STEUVERS' => array('line' => 69),
		'A_KFZ_SONST'    => array('line' => 70),
		'A_FREMDFZG'     => array('line' => 71),
		'A_KFZ_WEGE'     => array('line' => 72),
		'A_KFZ_EPAUSCH'  => array('line' => 73),
		'A_NABZ'         => array('line' => 74),
		// 3. Ermittlung des Gewinns (manual corrections)
		'G_78' => array('line' => 78), 'G_79' => array('line' => 79), 'G_80' => array('line' => 80),
		'G_81' => array('line' => 81), 'G_82' => array('line' => 82), 'G_83' => array('line' => 83),
		'G_84' => array('line' => 84), 'G_85' => array('line' => 85), 'G_86' => array('line' => 86),
		'G_87' => array('line' => 87), 'G_88' => array('line' => 88), 'G_89' => array('line' => 89),
		'G_91' => array('line' => 91), 'G_96' => array('line' => 96),
		// 4. Entnahmen und Einlagen
		'P_ENTNAHME'     => array('line' => 106),
		'P_EINLAGE'      => array('line' => 107),
		// neutral, not on the form
		'N_AV_KAUF'      => array(),
		'N_DARLEHEN'     => array(),
		'N_TRANSIT'      => array(),
	),
	'lines' => array(
		12 => array('Betriebseinnahmen als umsatzsteuerlicher Kleinunternehmer', 'E'),
		15 => array('Umsatzsteuerpflichtige Betriebseinnahmen', 'E'),
		16 => array('Umsatzsteuerfreie, nicht umsatzsteuerbare Betriebseinnahmen, § 13b UStG', 'E'),
		17 => array('Vereinnahmte Umsatzsteuer sowie Umsatzsteuer auf unentgeltliche Wertabgaben', 'E'),
		18 => array('Vom Finanzamt erstattete und ggf. verrechnete Umsatzsteuer', 'E'),
		19 => array('Veräußerung oder Entnahme von Anlagevermögen', 'E'),
		20 => array('Private Kfz-Nutzung', 'E', 'manual' => 1),
		21 => array('Sonstige Sach-, Nutzungs- und Leistungsentnahmen', 'E', 'manual' => 1),
		22 => array('Auflösung von Rücklagen und/oder Ausgleichsposten', 'E', 'manual' => 1),
		23 => array('Summe Betriebseinnahmen', 'E', 'sum' => array(12 => 1, 15 => 1, 16 => 1, 17 => 1, 18 => 1, 19 => 1, 20 => 1, 21 => 1, 22 => 1)),

		24 => array('Betriebsausgabenpauschale für bestimmte Berufsgruppen', 'A', 'manual' => 1),
		27 => array('Waren, Rohstoffe und Hilfsstoffe einschließlich der Nebenkosten', 'A'),
		29 => array('Bezogene Fremdleistungen', 'A'),
		30 => array('Ausgaben für eigenes Personal', 'A'),
		31 => array('AfA auf Grundstücke/grundstücksgleiche Rechte', 'A', 'manual' => 1),
		32 => array('AfA auf immaterielle Wirtschaftsgüter', 'A', 'manual' => 1),
		33 => array('AfA auf bewegliche Wirtschaftsgüter', 'A', 'manual' => 1),
		34 => array('Sonderabschreibungen nach § 7b EStG und § 7g Abs. 5 und 6 EStG', 'A', 'manual' => 1),
		35 => array('Herabsetzungsbeträge nach § 7g Abs. 2 Satz 3 EStG', 'A', 'manual' => 1),
		36 => array('Aufwendungen für geringwertige Wirtschaftsgüter nach § 6 Abs. 2 EStG', 'A'),
		37 => array('Auflösung Sammelposten nach § 6 Abs. 2a EStG', 'A', 'manual' => 1),
		38 => array('Restbuchwerte der ausgeschiedenen Anlagegüter', 'A', 'manual' => 1),
		39 => array('Miete/Pacht für Geschäftsräume und betrieblich genutzte Grundstücke', 'A'),
		40 => array('Aufwendungen für doppelte Haushaltsführung', 'A'),
		41 => array('Sonstige Aufwendungen für betrieblich genutzte Grundstücke', 'A'),
		43 => array('Aufwendungen für Telekommunikation', 'A'),
		44 => array('Übernachtungs- und Reisenebenkosten bei Geschäftsreisen', 'A'),
		45 => array('Fortbildungskosten (ohne Reisekosten)', 'A'),
		46 => array('Kosten für Rechts- und Steuerberatung, Buchführung', 'A'),
		47 => array('Miete/Leasing für bewegliche Wirtschaftsgüter (ohne Kfz)', 'A'),
		48 => array('Erhaltungsaufwendungen (ohne Gebäude und Kfz)', 'A'),
		49 => array('Beiträge, Gebühren, Abgaben und Versicherungen (ohne Gebäude und Kfz)', 'A'),
		50 => array('Laufende EDV-Kosten', 'A'),
		51 => array('Arbeitsmittel (z. B. Bürobedarf, Porto, Fachliteratur)', 'A'),
		52 => array('Kosten für Abfallbeseitigung und Entsorgung', 'A'),
		53 => array('Kosten für Verpackung und Transport', 'A'),
		54 => array('Werbekosten', 'A'),
		55 => array('Schuldzinsen zur Finanzierung von Anlagevermögen', 'A'),
		56 => array('Übrige Schuldzinsen', 'A'),
		57 => array('Gezahlte und nach § 15 UStG abziehbare Vorsteuerbeträge', 'A'),
		58 => array('An das Finanzamt gezahlte und ggf. verrechnete Umsatzsteuer', 'A'),
		59 => array('Rücklagen, stille Reserven und/oder Ausgleichsposten', 'A', 'manual' => 1),
		60 => array('Übrige unbeschränkt abziehbare Betriebsausgaben', 'A'),
		62 => array('Geschenke', 'A', 'twocol' => 1),
		63 => array('Bewirtungsaufwendungen', 'A', 'twocol' => 1),
		64 => array('Verpflegungsmehraufwendungen', 'A', 'twocol' => 1),
		65 => array('Aufwendungen für ein häusliches Arbeitszimmer', 'A', 'twocol' => 1),
		66 => array('Tagespauschale für die Tätigkeit in der häuslichen Wohnung', 'A', 'twocol' => 1, 'manual' => 1),
		67 => array('Sonstige beschränkt abziehbare Betriebsausgaben', 'A', 'twocol' => 1),
		68 => array('Kfz: Leasingkosten', 'A'),
		69 => array('Kfz: Steuern, Versicherungen und Maut', 'A'),
		70 => array('Sonstige tatsächliche Fahrtkosten ohne AfA und Zinsen', 'A'),
		71 => array('Fahrtkosten für nicht zum Betriebsvermögen gehörende Fahrzeuge', 'A'),
		72 => array('Fahrtkosten Wohnung – erste Betriebsstätte (Kürzung, abzüglich)', 'A', 'manual' => 1),
		73 => array('Mindestens abziehbare Fahrtkosten (Entfernungspauschale)', 'A', 'manual' => 1),
		74 => array('Nicht abziehbare Beträge (abzüglich)', 'A', 'manual' => 1),
		75 => array('Summe Betriebsausgaben', 'A', 'sum' => array(
			24 => 1, 27 => 1, 29 => 1, 30 => 1, 31 => 1, 32 => 1, 33 => 1, 34 => 1, 35 => 1, 36 => 1, 37 => 1, 38 => 1,
			39 => 1, 40 => 1, 41 => 1, 43 => 1, 44 => 1, 45 => 1, 46 => 1, 47 => 1, 48 => 1, 49 => 1, 50 => 1,
			51 => 1, 52 => 1, 53 => 1, 54 => 1, 55 => 1, 56 => 1, 57 => 1, 58 => 1, 59 => 1, 60 => 1,
			62 => 1, 63 => 1, 64 => 1, 65 => 1, 66 => 1, 67 => 1, 68 => 1, 69 => 1, 70 => 1, 71 => 1,
			72 => -1, 73 => 1, 74 => -1)),

		76 => array('Summe der Betriebseinnahmen (Übertrag aus Zeile 23)', 'G', 'sum' => array(23 => 1)),
		77 => array('abzüglich Summe der Betriebsausgaben (Übertrag aus Zeile 75)', 'G', 'sum' => array(75 => 1)),
		78 => array('abzüglich steuerfreier Einnahmen nach § 3 Nr. 26, 26a, 26b EStG', 'G', 'manual' => 1),
		79 => array('abzüglich steuerfreier Einnahmen nach § 3 EStG (übrige)', 'G', 'manual' => 1),
		80 => array('abzüglich steuerfreier Einnahmen nach § 3a EStG', 'G', 'manual' => 1),
		81 => array('zuzüglich nicht abziehbarer BA i. Z. m. § 3 Nr. 26, 26a, 26b EStG', 'G', 'manual' => 1),
		82 => array('zuzüglich nicht abziehbarer BA nach § 3c Abs. 1 EStG', 'G', 'manual' => 1),
		83 => array('zuzüglich nicht abziehbarer BA nach § 3c Abs. 4 EStG', 'G', 'manual' => 1),
		84 => array('zuzüglich Hinzurechnung Investitionsabzugsbeträge § 7g EStG aus 2022', 'G', 'manual' => 1),
		85 => array('zuzüglich Hinzurechnung Investitionsabzugsbeträge § 7g EStG aus 2023', 'G', 'manual' => 1),
		86 => array('zuzüglich Hinzurechnung Investitionsabzugsbeträge § 7g EStG aus 2024', 'G', 'manual' => 1),
		87 => array('zuzüglich Gewinnzuschlag nach § 6c i. V. m. § 6b Abs. 7 und 10 EStG', 'G', 'manual' => 1),
		88 => array('abzüglich Investitionsabzugsbeträge nach § 7g Abs. 1 EStG', 'G', 'manual' => 1),
		89 => array('Hinzurechnungen und Abrechnungen bei Wechsel der Gewinnermittlungsart (+/−)', 'G', 'manual' => 1),
		90 => array('Übertrag (Summe/Differenz Zeilen 76 bis 89)', 'G', 'sum' => array(
			76 => 1, 77 => -1, 78 => -1, 79 => -1, 80 => -1, 81 => 1, 82 => 1, 83 => 1,
			84 => 1, 85 => 1, 86 => 1, 87 => 1, 88 => -1, 89 => 1)),
		91 => array('Ergebnisanteile aus Beteiligungen an Personengesellschaften (+/−)', 'G', 'manual' => 1),
		92 => array('Korrigierter Gewinn/Verlust', 'G', 'sum' => array(90 => 1, 91 => 1)),
		95 => array('Steuerpflichtiger Gewinn/Verlust vor Anwendung des § 4 Abs. 4a EStG', 'G', 'sum' => array(92 => 1)),
		96 => array('Hinzurechnungsbetrag nach § 4 Abs. 4a EStG', 'G', 'manual' => 1),
		97 => array('Steuerpflichtiger Gewinn/Verlust', 'G', 'sum' => array(95 => 1, 96 => 1)),

		106 => array('Entnahmen einschließlich Sach-, Leistungs- und Nutzungsentnahmen', 'P'),
		107 => array('Einlagen einschließlich Sach-, Leistungs- und Nutzungseinlagen', 'P'),
	),
);
